<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace common\components\authclient\clients;

use yii\authclient\OAuth2;
use yii\authclient\OAuthToken;

use yii\authclient\InvalidResponseException;
use yii\helpers\ArrayHelper;
use yii\httpclient\Request;
use yii\httpclient\Response;

/**
 * Demo allows authentication via Demo OAuth.
 *
 * In order to use Demo OAuth you must register your application at <http://connect.demo.com/>.
 *
 * Example application configuration:
 *
 * ```php
 * 'components' => [
 *     'authClientCollection' => [
 *         'class' => 'yii\authclient\Collection',
 *         'clients' => [
 *             'demo' => [
 *                 'class' => 'common\components\authclient\clients\QqAuth',
 *                 'clientId' => 'demo_client_id',
 *                 'clientSecret' => 'demo_client_secret',
 *             ],
 *         ],
 *     ]
 *     // ...
 * ]
 * ```
 *
 * @see http://connect.demo.com/
 *
 * @author Shadow <hongyukeji@126.com>
 * @since 1.0
 */
class DemoAuth extends OAuth2
{
    /**
     * @Step1：获取Authorization Code
     */
    public $authUrl = 'https://graph.demo.com/oauth2.0/authorize';

    /**
     * @Step2：通过Authorization Code获取Access Token
     */
    public $tokenUrl = 'https://graph.demo.com/oauth2.0/token';

    /**
     * {@inheritdoc}
     */
    public $apiBaseUrl = 'https://graph.demo.com';


    public $scope = 'get_user_info';

    public $attributeNames = [
        'nickname',
        'figureurl_demo_2',
    ];

    public $autoRefreshAccessToken = false;

    public $autoExchangeAccessToken = false;

    public $clientAuthCodeUrl = 'https://graph.demo.com/oauth/client_code';


    /**
     * {@inheritdoc}
     */
    /*public function init()
    {
        parent::init();
        if ($this->scope === null) {
            $this->scope = implode(',', [
                'get_user_info',
            ]);
        }
    }*/


    /**
     * @return array
     * @see http://wiki.connect.demo.com/%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7openid_oauth2-0
     * @see http://wiki.connect.demo.com/get_user_info
     */
    protected function initUserAttributes()
    {
        //return $this->api('oauth2.0/me', 'GET');

        $userInfo =[];

        $attributes = $this->api('oauth2.0/me', 'GET');

        // 获取用户信息
        $user = $this->api("user/get_user_info", 'GET', [
            'access_token' => $this->getAccessToken()->params['access_token'],
            'oauth_consumer_key' => $attributes['client_id'],
            'openid' => $attributes['openid'],
        ]);

        // 处理赋值 client_key openid username avatar_url
        $userInfo['client_key'] = $this->getId();
        $userInfo['source_id'] = $attributes['openid'];
        $userInfo['username'] = $user['nickname'];
        $userInfo['avatar_url'] = $user['figureurl_qq_2'];

        // 合并数组
        //$result = ArrayHelper::merge($attributes, $userInfo);

        return $userInfo;

    }

    public function buildAuthUrl(array $params = [])
    {
        $params = ['app_id' => $this->clientId,];
        return parent::buildAuthUrl($params); // TODO: Change the autogenerated stub
    }

    protected function defaultName()
    {
        return 'demo';
    }

    protected function defaultTitle()
    {
        return 'Demo';
    }


    protected function defaultViewOptions()
    {
        return [
            'popupWidth' => 860,
            'popupHeight' => 480,
        ];
    }

    protected function sendRequest($request)
    {
        $response = $request->send();
        if (!$response->getIsOk()) {
            throw new InvalidResponseException($response, 'Request failed with code: ' . $response->getStatusCode() . ', message: ' . $response->getContent());
        }
        $this->processResult($response);
        return $response->getData();
    }

    protected function processResult(Response $response)
    {
        $content = $response->getContent();
        if (strpos($content, "callback") !== 0) {
            return;
        }
        $lpos = strpos($content, "(");
        $rpos = strrpos($content, ")");
        $content = substr($content, $lpos + 1, $rpos - $lpos - 1);
        $content = trim($content);
        $response->setContent($content);
    }
}
