<?php
/**
 * eBestMall
 * ============================================================================
 * Copyright 2015-2017 HongYuKeJi.Co.Ltd. All rights reserved.
 * Http://www.hongyuvip.com
 * ----------------------------------------------------------------------------
 * 仅供学习交流使用，如需商用请购买商用版权。
 * 堂堂正正做人，踏踏实实做事。
 * ----------------------------------------------------------------------------
 * Author: Shadow  QQ: 1527200768  Time: 2017/12/22 13:36
 * E-mail: hongyukeji@126.com
 * ============================================================================
 */

namespace common\components\authclient\clients;

use yii\authclient\OAuth2;
use yii\authclient\InvalidResponseException;
use yii\httpclient\Request;
use yii\httpclient\Response;

/**
 * WeiBo allows authentication via WeiBo OAuth.
 *
 * In order to use WeiBo OAuth you must register your application at <http://open.weibo.com/>.
 *
 * Example application configuration:
 *
 * ```php
 * 'components' => [
 *     'authClientCollection' => [
 *         'class' => 'yii\authclient\Collection',
 *         'clients' => [
 *             'weibo' => [
 *                 'class' => 'common\components\authclient\clients\WeiBoAuth',
 *                 'clientId' => 'weibo_client_id',
 *                 'clientSecret' => 'weibo_client_secret',
 *             ],
 *         ],
 *     ]
 *     // ...
 * ]
 * ```
 *
 * @see http://open.weibo.com/
 *
 * @author Shadow <hongyukeji@126.com>
 * @since 1.0
 */
class WeiBoAuth extends OAuth2
{
    // 授权回调地址 http://www.ebestmall.dev/auth/auth?authclient=weibo

    public $authUrl = 'https://api.weibo.com/oauth2/authorize';

    public $tokenUrl = 'https://api.weibo.com/oauth2/access_token';

    public $apiBaseUrl = 'https://api.weibo.com';

    /**
     * @return array
     * @see http://open.weibo.com/tools/console
     * @see http://open.weibo.com/wiki/2/users/show
     */
    protected function initUserAttributes()
    {
        $user = $this->api('2/users/show.json', 'get', [
            'uid' => $this->getAccessToken()->params['uid'],
        ]);

        $userInfo['client_key'] = $this->getId();
        $userInfo['source_id'] = $user['id'];
        $userInfo['username'] = $user['name'];
        $userInfo['avatar_url'] = $user['profile_image_url'];

        return $userInfo;
    }

    public function buildAuthUrl(array $params = [])
    {
        $params = ['display' => 'client',];
        return parent::buildAuthUrl($params); // TODO: Change the autogenerated stub
    }

    protected function defaultName()
    {
        return 'weibo';
    }

    protected function defaultTitle()
    {
        return 'WeiBo';
    }

}