<?php
/**
 * eBestMall
 * ============================================================================
 * Copyright 2015-2017 HongYuKeJi.Co.Ltd. All rights reserved.
 * Http://www.hongyuvip.com
 * ----------------------------------------------------------------------------
 * 仅供学习交流使用，如需商用请购买商用版权。
 * 堂堂正正做人，踏踏实实做事。
 * ----------------------------------------------------------------------------
 * Author: Shadow  QQ: 1527200768 & 13391528  Time: 2017/11/18 21:55
 * E-mail: hongyukeji@126.com
 * ============================================================================
 */

namespace app\controllers;

use Yii;
use yii\web\Controller as BaseController;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class Controller extends BaseController
{
    protected $onlyActions = [''];
    protected $exceptActions = [];
    protected $validateActions = [];
    protected $verbsActions = [];

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => $this->onlyActions,
                'except' => $this->exceptActions,
                'rules' => [
                    [
                        'actions' => $this->validateActions ?: [],
                        'allow' => true,
                        'roles' => ['@'],   // user
                    ],
                    [
                        'actions' => $this->validateActions ?: [],
                        'allow' => false,
                        'roles' => ['?'],   // guest
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => $this->verbs,
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //Yii::$app->language = 'zh-CN';

        // 模块调用
        //$mobile = Yii::$app->getModule('mobile');
        //$mobile->runAction('default/index');

        // 判断是否是移动设备访问
        $device = new \Detection\MobileDetect();
        if ($device->isMobile()) {
            return $this->redirect(['/mobile']);
        }

    }
}