<?php

namespace app\controllers;

use Yii;
use yii\web\Controller as BaseController;
use Detection\MobileDetect;


class Controller extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $cookies = Yii::$app->request->cookies;

        $language = $cookies->getValue('language', 'zh-CN');

        Yii::$app->language = $language;

        // 判断是否是移动设备访问
        $device = new MobileDetect();
        if ($device->isMobile()) {
            $this->redirect(['/mobile']);
        }


    }
}